### ISSUE TITLE
error code: 651 message: seqno not in db

### ISSUE THREAD

**Issue by Kambez001** [tonkeeper/opentonapi#129]
Hello
I use Docker with this command "docker run -d -p8081:8081 tonkeeper/opentonapi"

when i request to my server, i get error but when i request to tonapi.io, it's work fine !

http://127.0.0.01:8081/v2/blockchain/blocks/(0,8000000000000000,35604934)/transactions

**Comment by mr-tron** [comment]
on public liteservers some blocks can be unavailable. you shoud user your own archive node if you want to request old blocks.
