### ISSUE TITLE
404 when get tx of testnet da5886713fe53229dd4f8ceced7ec62890f2c1c6629bf74085bd4e1a8c8e0b95

### ISSUE THREAD

**Issue by yangyile1990** [tonkeeper/opentonapi#198]
use "https://testnet.tonapi.io"

**Comment by mr-tron** [comment]
https://testnet.tonviewer.com/transaction/da5886713fe53229dd4f8ceced7ec62890f2c1c6629bf74085bd4e1a8c8e0b95

**Comment by yangyile1990** [comment]
```
func TestTon_GetTxById(t *testing.T) {
	client2, err := client.NewClient("https://testnet.tonapi.io")
	require.NoError(t, err)
	txid := "da5886713fe53229dd4f8ceced7ec62890f2c1c6629bf74085bd4e1a8c8e0b95"
	transaction, err := client2.GetBlockchainTransaction(context.Background(), client.GetBlockchainTransactionParams{
		TransactionID: txid,
	})
	t.Log(cjson.NeatString(transaction))
}
```
the transaction is nil.

**Comment by yangyile1990** [comment]
```
func TestTon_GetTxById01(t *testing.T) {
	client2, err := client.NewClient("https://tonapi.io")
	require.NoError(t, err)
	txid := "4b47fdce950797521080d49b2a310e3d4aa80e5fd0bde44e6cdd71c5ef81ee08"
	transaction, err := client2.GetBlockchainTransaction(context.Background(), client.GetBlockchainTransactionParams{
		TransactionID: txid,
	})
	require.NoError(t, err)
	t.Log(cjson.NeatString(transaction))
}
```
but this is ok.

**Comment by yangyile1990** [comment]
func (w *Wallet) SendV2(
	ctx context.Context,
	waitingConfirmation time.Duration,
	messages ...Sendable,
) (ton.Bits256, error)

after exec this I get a hash da5886713fe53229dd4f8ceced7ec62890f2c1c6629bf74085bd4e1a8c8e0b95

while the hash is not tx hash. (can not search by /v2/blockchain/transactions/)

but is bb4f07ec147756fe3c1ef57d7397f6f19e4cd12869be0e96940a6f91c703bed4

https://testnet.tonviewer.com/transaction/da5886713fe53229dd4f8ceced7ec62890f2c1c6629bf74085bd4e1a8c8e0b95

why?

how to use da5886713fe53229dd4f8ceced7ec62890f2c1c6629bf74085bd4e1a8c8e0b95 get bb4f07ec147756fe3c1ef57d7397f6f19e4cd12869be0e96940a6f91c703bed4
