### ISSUE TITLE
live scammer

### ISSUE THREAD

**Issue by MarijaMaca** [tonkeeper/opentonapi#299]
> _EQArDbPZD9zEZvom9jI7iD5zlfAQSAnRtXh0BdK53T4OyIKy_

   this person is a real life-scam, using "trading bot" over Tarmex.. 
It should be some button with option like "return crypto and report address/ person/ bot" 

![Screenshot_11](https://github.com/tonkeeper/opentonapi/assets/147364339/59253495-d4f7-422b-88a8-36dc46796d91)

**Comment by mr-tron** [comment]
we are just opensource project for converting one api to another
