### ISSUE TITLE
With:

### ISSUE THREAD

**Issue by wlofman021** [tonkeeper/opentonapi#393]
With:
- Tact 1.4.0 (#5)
- FunC 0.4.4 (#1)

_Originally posted by @novusnota in https://github.com/novusnota/prism-ton/issues/3_

**Comment by novusnota** [comment]
Now this is a weird kind of spam, please delete this ↑

**Comment by mm8191** [comment]
باتشکر و احترام ونااحترام کلاهبرداری در زمانه ای ک چوس بزنی اونور کره زمین میفهمه یک بی عقلی است انجام بدی
