### ISSUE TITLE
All liteservers are unavailable when running tests

### ISSUE THREAD

**Issue by artiship** [tonkeeper/opentonapi#508]
![image](https://github.com/user-attachments/assets/f2eee7c8-b807-447f-b5f2-eb3228f7e8bc)

I'm using GoLand IDE. If I run tests like in `bath_test.go`, it'll complain

```
Error:      	Expected nil, but got: &errors.errorString{s:"all liteservers are unavailable"}
```
![image](https://github.com/user-attachments/assets/0aea0b4d-cfce-436b-8254-806e4fba64b2)

The error came from here, and I didn't have any `LITE_SERVERS` configured at my workspace. Anyone ever came across the same issue?

**Comment by artiship** [comment]
it's my env

**Comment by FedeCaffaro** [comment]
How did you solve it? I have the same issue

**Comment by artiship** [comment]
It's my working environment banded  the access to ton network, so I changed to a different place solved the issue
