### ISSUE TITLE
Incorrect in msg hash 

### ISSUE THREAD

**Issue by dathuynh1108** [tonkeeper/opentonapi#572]
Hello, i have make a jetton transfer transaction and save external msg hash to confirm the transaction. But api v2/blockchain/transactions/  return   "error": "entity not found". I have checked and found that the in_msg hash of jetton transfer is incorrect (get by transaction hash `fe4df7b482a31981274d6232887f102812b9b7106fb627909f346a3e1ea5f351`)

https://testnet.tonapi.io/v2/blockchain/transactions/fe4df7b482a31981274d6232887f102812b9b7106fb627909f346a3e1ea5f351

It return me the in msg hash is: `42fbe403afe8c495cf323a3293ff1062031e6989344389d7f133d27d35f0bc33` (mean `QvvkA6/oxJXPMjoyk/8QYgMeaYk0Q4nX8TPSfTXwvDM=` in base64)

When i filter it by another viewer (tonscan), tonscan return me not found that hash (the correct hash is `QpNatGrhFnwpO2/BseDbz/T6fP7dTVE5P9zuXBtrsM0=`, that also is saved in my database when send transaction).

So i think it make both /v2/blockchain/messages/{msg_id}/transaction and /v2/blockchain/transactions/{transaction_id} return not found when i filter by correct hash

Ton scan transaction: https://testnet.tonscan.org/tx/%2Fk33tIKjGYEnTWIyiH8QKBK5txBvtieQnzRqPh6l81E=

**Comment by unixvb** [comment]
The same problem occurs when using the BOC hex hash. It previously worked fine, but now it returns `entity not found` in most cases.

Here’s the code used to convert the BOC string from `@tonconnect` to a hex hash:
```
const boc = response.boc; // response from tonConnectUI.sendTransaction fn
const cell = Cell.fromBoc(Buffer.from(boc, 'base64'))[0];
const hash =  cell.hash().toString('hex');
```

**Comment by mr-tron** [comment]
fixeid. please subscribe on https://t.me/tonconsole_com for future updates
